version: "2.1"

services:
  web:
    container_name: web
    image: "docker171085/listing_web:1.0.0"
    ports:
      - 80:3000
  api:
    container_name: api
    image: "docker171085/listing_api"
    mem_limit: 1024m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - AWS_ACCESS_KEY=AKIA2ISJLKP2S65IIKH7
      - AWS_SECRET_KEY=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
      - AWS_REGION=us-east-1
      - BUCKET=mahalisting
      - IMAGE_FOLDER=images
  postgres:
    container_name: pgdb
    image: postgres:9.6-alpine
    environment:
      - 'POSTGRES_ROOT_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    ports:
      - "54321:5432"